slam_toolbox:
  ros__parameters:
    mode: "mapping"
    use_sim_time: true
    odom_frame: "odom"
    map_frame: "map" 
    base_frame: "base_link"
    scan_topic: "/scan"
    resolution: 0.05
    max_laser_range: 10.0
    minimum_time_interval: 0.2
    throttle_scans: 1
    do_loop_closing: true
    loop_closure_search_distance: 5.0
    publish_occupancy_grid: true